// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MANUALLY MODIFY.
// YOUR MANUAL CHANGES WILL BE OVERWRITTEN UPON THE NEXT STUDIO_PROJECT_CONF SYNC.

// This file contains your project's publicly-facing Firebase configuration.
// You are free to move this file to a different location, but remember to update any imports.

// IMPORTANT: DO NOT ADD ANY SECRETS TO THIS FILE.
// This file is stored in version control and contains information that is necessary for your client-side application to communicate with your Firebase project.
// Secrecy is not required for the values below because all access to your Firebase resources is secured using Firebase Security Rules.
// For more information, see: https://firebase.google.com/docs/projects/learn-more#config-files-objects

export const firebaseConfig = {
  apiKey: "AIzaSyARrBNrKda7gj2mvyQD1YsX6VPHw84kLcs",
  authDomain: "ateaco-fb.firebaseapp.com",
  projectId: "ateaco-fb",
  storageBucket: "ateaco-fb.firebasestorage.app",
  messagingSenderId: "274248485200",
  appId: "1:274248485200:web:ace7fd03eabfcebfc4c455",
  measurementId: "G-SK8GCSHJEE"
};
